version: 2.1 

defaults: &defaults
  working_directory: ~/chargejs
  docker:
    - image: circleci/node:12.16

jobs: 
  build: 
    <<: *defaults  
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install-chargejs
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:report
      - persist_to_workspace:
          root: ~/chargejs
          paths: .
  deploy:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/chargejs
      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master