version: 2.1 
jobs: 
  build: 
    working_directory: ~/chargejs
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-chargejs
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:report
      - run:
          name: Send coverage report to Code Climate
          command:
              # nyc report requires that nyc has already been run,
              # which creates the .nyc_output folder containing necessary data
              ./cc-test-reporter after-build -t lcov
          when: always